HOME: /t3home/frejalom
USER: frejalom
SLURM_JOB_ID: 244147
HOSTNAME: t3wn60
CMSSW RELEASE BASE  /cvmfs/cms.cern.ch/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_2_0_pre4
%MSG-i AlpakaService:  (NoModuleName) 02-Apr-2025 08:44:08 CEST pre-events
AlpakaServiceSerialSync succesfully initialised.
Found 1 device:
  - Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
%MSG
02-Apr-2025 08:44:12 CEST  Initiating request to open file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root
[2025-04-02 08:44:12.364840 +0200][Error  ][XRootDTransport   ][84969] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:12.364935 +0200][Error  ][XRootDTransport   ][84969] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:12.364956 +0200][Error  ][AsyncSock         ][84969] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:12.365019 +0200][Error  ][PostMaster        ][84969] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:12.365030 +0200][Error  ][PostMaster        ][84969] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:12.365042 +0200][Error  ][XRootD            ][84969] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root). Trying to recover.
[2025-04-02 08:44:12.365214 +0200][Error  ][XRootD            ][84969] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/36db064e-7f57-490e-80f9-39310c13e3ea.root). Trying to recover.
[2025-04-02 08:44:12.365242 +0200][Error  ][XRootD            ][84969] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/a00553ad-3a11-4010-a8d2-79e54a25295c.root). Trying to recover.
[2025-04-02 08:44:12.365269 +0200][Error  ][XRootD            ][84969] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_query (code: kXR_Qconfig, arg length: 9). Trying to recover.
[2025-04-02 08:44:13.374196 +0200][Error  ][XRootDTransport   ][84969] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:13.374245 +0200][Error  ][XRootDTransport   ][84969] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:13.374254 +0200][Error  ][AsyncSock         ][84969] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:13.374279 +0200][Error  ][PostMaster        ][84969] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:13.374285 +0200][Error  ][PostMaster        ][84969] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:13.374291 +0200][Error  ][XRootD            ][84969] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:44:13 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root?xrdcl.requuid=6425321f-db69-4850-a05b-46763c8bfd38.
%MSG
[2025-04-02 08:44:13.393192 +0200][Error  ][XRootDTransport   ][84969] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:13.393242 +0200][Error  ][XRootDTransport   ][84969] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:13.393251 +0200][Error  ][AsyncSock         ][84969] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:13.393277 +0200][Error  ][PostMaster        ][84969] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:13.393282 +0200][Error  ][PostMaster        ][84969] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:13.393288 +0200][Error  ][XRootD            ][84969] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root?tried=, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:44:13 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root?tried=&xrdcl.requuid=66e41d04-7098-43a0-92fd-71946f4f79dc.
%MSG
----- Begin Fatal Exception 02-Apr-2025 08:44:13 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root'
   Additional Info:
      [a] Input file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root could not be opened.
      [b] XrdCl::File::Open(name='root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root', flags=0x10, permissions=0660) => error '[FATAL] Auth failed: No protocols left to try' (errno=0, code=204). No additional data servers were found.
      [c] Last URL tried: root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e5d805f2-3e83-477a-9b65-ebba57e74b52.root?tried=&xrdcl.requuid=66e41d04-7098-43a0-92fd-71946f4f79dc
      [d] Problematic data server: t3dcachedb.psi.ch:1094
      [e] Disabled source: t3dcachedb.psi.ch:1094
----- End Fatal Exception -------------------------------------------------
logfile
pv_cfg.py
cp: cannot stat 'pv.root': No such file or directory
