HOME: /t3home/frejalom
USER: frejalom
SLURM_JOB_ID: 244223
HOSTNAME: t3wn60
CMSSW RELEASE BASE  /cvmfs/cms.cern.ch/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_2_0_pre4
%MSG-i AlpakaService:  (NoModuleName) 02-Apr-2025 08:51:22 CEST pre-events
AlpakaServiceSerialSync succesfully initialised.
Found 1 device:
  - Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
%MSG
02-Apr-2025 08:51:27 CEST  Initiating request to open file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root
[2025-04-02 08:51:28.073450 +0200][Error  ][XRootDTransport   ][100670] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:51:28.073569 +0200][Error  ][XRootDTransport   ][100670] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:51:28.073598 +0200][Error  ][AsyncSock         ][100670] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:51:28.073666 +0200][Error  ][PostMaster        ][100670] [t3dcachedb.psi.ch:1094] elapsed = 1, pConnectionWindow = 31 seconds.
[2025-04-02 08:51:28.073681 +0200][Error  ][PostMaster        ][100670] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:51:28.073697 +0200][Error  ][XRootD            ][100670] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root). Trying to recover.
[2025-04-02 08:51:28.073817 +0200][Error  ][XRootD            ][100670] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/d580227c-5f88-4465-978d-fcee13348973.root). Trying to recover.
[2025-04-02 08:51:28.073856 +0200][Error  ][XRootD            ][100670] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e2608780-3aa8-47b1-9ab8-234509e01243.root). Trying to recover.
[2025-04-02 08:51:28.073891 +0200][Error  ][XRootD            ][100670] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_query (code: kXR_Qconfig, arg length: 9). Trying to recover.
[2025-04-02 08:51:29.091231 +0200][Error  ][XRootDTransport   ][100670] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:51:29.091314 +0200][Error  ][XRootDTransport   ][100670] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:51:29.091330 +0200][Error  ][AsyncSock         ][100670] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:51:29.091368 +0200][Error  ][PostMaster        ][100670] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:51:29.091377 +0200][Error  ][PostMaster        ][100670] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:51:29.091386 +0200][Error  ][XRootD            ][100670] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:51:29 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root?xrdcl.requuid=d6d02b45-a639-46a5-9c98-c2d632313e96.
%MSG
[2025-04-02 08:51:29.119066 +0200][Error  ][XRootDTransport   ][100670] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:51:29.119150 +0200][Error  ][XRootDTransport   ][100670] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:51:29.119164 +0200][Error  ][AsyncSock         ][100670] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:51:29.119201 +0200][Error  ][PostMaster        ][100670] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:51:29.119210 +0200][Error  ][PostMaster        ][100670] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:51:29.119219 +0200][Error  ][XRootD            ][100670] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root?tried=, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:51:29 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root?tried=&xrdcl.requuid=3dfdeb32-0b7b-42af-aa7b-0bf1c35a0029.
%MSG
----- Begin Fatal Exception 02-Apr-2025 08:51:29 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root'
   Additional Info:
      [a] Input file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root could not be opened.
      [b] XrdCl::File::Open(name='root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root', flags=0x10, permissions=0660) => error '[FATAL] Auth failed: No protocols left to try' (errno=0, code=204). No additional data servers were found.
      [c] Last URL tried: root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/e7d77eaa-972e-4e28-90b2-1d325cbe5dde.root?tried=&xrdcl.requuid=3dfdeb32-0b7b-42af-aa7b-0bf1c35a0029
      [d] Problematic data server: t3dcachedb.psi.ch:1094
      [e] Disabled source: t3dcachedb.psi.ch:1094
----- End Fatal Exception -------------------------------------------------
logfile
pv_cfg.py
cp: cannot stat 'pv.root': No such file or directory
