HOME: /t3home/frejalom
USER: frejalom
SLURM_JOB_ID: 244151
HOSTNAME: t3wn60
CMSSW RELEASE BASE  /cvmfs/cms.cern.ch/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_2_0_pre4
%MSG-i AlpakaService:  (NoModuleName) 02-Apr-2025 08:44:22 CEST pre-events
AlpakaServiceSerialSync succesfully initialised.
Found 1 device:
  - Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
%MSG
02-Apr-2025 08:44:25 CEST  Initiating request to open file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root
[2025-04-02 08:44:25.936955 +0200][Error  ][XRootDTransport   ][85952] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:25.937039 +0200][Error  ][XRootDTransport   ][85952] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:25.937058 +0200][Error  ][AsyncSock         ][85952] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:25.937118 +0200][Error  ][PostMaster        ][85952] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:25.937127 +0200][Error  ][PostMaster        ][85952] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:25.937138 +0200][Error  ][XRootD            ][85952] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root). Trying to recover.
[2025-04-02 08:44:25.937298 +0200][Error  ][XRootD            ][85952] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/b80b4890-f6d6-456b-b845-681ca9d7ccd4.root). Trying to recover.
[2025-04-02 08:44:25.937350 +0200][Error  ][XRootD            ][85952] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/6cd398d2-51f8-4cd9-9e16-92e3e14d61e8.root). Trying to recover.
[2025-04-02 08:44:25.963519 +0200][Error  ][XRootDTransport   ][85952] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:25.963591 +0200][Error  ][XRootDTransport   ][85952] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:25.963608 +0200][Error  ][AsyncSock         ][85952] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:25.963643 +0200][Error  ][PostMaster        ][85952] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:25.963649 +0200][Error  ][PostMaster        ][85952] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:25.963655 +0200][Error  ][XRootD            ][85952] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_query (code: kXR_Qconfig, arg length: 9). Trying to recover.
[2025-04-02 08:44:26.957776 +0200][Error  ][XRootDTransport   ][85952] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:26.957835 +0200][Error  ][XRootDTransport   ][85952] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:26.957845 +0200][Error  ][AsyncSock         ][85952] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:26.957870 +0200][Error  ][PostMaster        ][85952] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:26.957876 +0200][Error  ][PostMaster        ][85952] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:26.957888 +0200][Error  ][XRootD            ][85952] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:44:26 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root?xrdcl.requuid=ef5ffbce-9182-474b-82b6-cc34112ce6e2.
%MSG
[2025-04-02 08:44:26.977231 +0200][Error  ][XRootDTransport   ][85952] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:26.977287 +0200][Error  ][XRootDTransport   ][85952] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:26.977297 +0200][Error  ][AsyncSock         ][85952] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:26.977325 +0200][Error  ][PostMaster        ][85952] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:26.977331 +0200][Error  ][PostMaster        ][85952] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:26.977337 +0200][Error  ][XRootD            ][85952] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root?tried=, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:44:26 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root?tried=&xrdcl.requuid=7e157039-9dfc-42aa-914a-6d6b11f3e69d.
%MSG
----- Begin Fatal Exception 02-Apr-2025 08:44:26 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root'
   Additional Info:
      [a] Input file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root could not be opened.
      [b] XrdCl::File::Open(name='root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root', flags=0x10, permissions=0660) => error '[FATAL] Auth failed: No protocols left to try' (errno=0, code=204). No additional data servers were found.
      [c] Last URL tried: root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/4b01730a-f29c-4a6d-9545-b6b486c8d06e.root?tried=&xrdcl.requuid=7e157039-9dfc-42aa-914a-6d6b11f3e69d
      [d] Problematic data server: t3dcachedb.psi.ch:1094
      [e] Disabled source: t3dcachedb.psi.ch:1094
----- End Fatal Exception -------------------------------------------------
logfile
pv_cfg.py
cp: cannot stat 'pv.root': No such file or directory
