HOME: /t3home/frejalom
USER: frejalom
SLURM_JOB_ID: 244176
HOSTNAME: t3wn60
CMSSW RELEASE BASE  /cvmfs/cms.cern.ch/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_2_0_pre4
%MSG-i AlpakaService:  (NoModuleName) 02-Apr-2025 08:44:44 CEST pre-events
AlpakaServiceSerialSync succesfully initialised.
Found 1 device:
  - Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
%MSG
02-Apr-2025 08:44:50 CEST  Initiating request to open file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root
[2025-04-02 08:44:50.241545 +0200][Error  ][XRootDTransport   ][90868] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:50.241608 +0200][Error  ][XRootDTransport   ][90868] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:50.241624 +0200][Error  ][AsyncSock         ][90868] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:50.241666 +0200][Error  ][PostMaster        ][90868] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:50.241676 +0200][Error  ][PostMaster        ][90868] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:50.241686 +0200][Error  ][XRootD            ][90868] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root). Trying to recover.
[2025-04-02 08:44:50.241797 +0200][Error  ][XRootD            ][90868] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/2c145a63-991c-499a-916d-64de4a7c8c74.root). Trying to recover.
[2025-04-02 08:44:50.241826 +0200][Error  ][XRootD            ][90868] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/06389bf4-6539-46ee-a319-a60bb719dc16.root). Trying to recover.
[2025-04-02 08:44:50.241851 +0200][Error  ][XRootD            ][90868] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_query (code: kXR_Qconfig, arg length: 9). Trying to recover.
[2025-04-02 08:44:51.288578 +0200][Error  ][XRootDTransport   ][90868] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:51.288656 +0200][Error  ][XRootDTransport   ][90868] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:51.288678 +0200][Error  ][AsyncSock         ][90868] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:51.288722 +0200][Error  ][PostMaster        ][90868] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:51.288737 +0200][Error  ][PostMaster        ][90868] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:51.288753 +0200][Error  ][XRootD            ][90868] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:44:51 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root?xrdcl.requuid=375c28de-22fa-484d-af4d-7539b9a09030.
%MSG
[2025-04-02 08:44:51.328006 +0200][Error  ][XRootDTransport   ][90868] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:44:51.328075 +0200][Error  ][XRootDTransport   ][90868] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:44:51.328096 +0200][Error  ][AsyncSock         ][90868] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:44:51.328137 +0200][Error  ][PostMaster        ][90868] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:44:51.328151 +0200][Error  ][PostMaster        ][90868] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:44:51.328164 +0200][Error  ][XRootD            ][90868] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root?tried=, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:44:51 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root?tried=&xrdcl.requuid=381d1c5e-3b3c-4de0-853d-cbc28f876c3d.
%MSG
----- Begin Fatal Exception 02-Apr-2025 08:44:51 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root'
   Additional Info:
      [a] Input file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root could not be opened.
      [b] XrdCl::File::Open(name='root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root', flags=0x10, permissions=0660) => error '[FATAL] Auth failed: No protocols left to try' (errno=0, code=204). No additional data servers were found.
      [c] Last URL tried: root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/f6600449-5fa8-4e84-81cf-4f9df8425f9c.root?tried=&xrdcl.requuid=381d1c5e-3b3c-4de0-853d-cbc28f876c3d
      [d] Problematic data server: t3dcachedb.psi.ch:1094
      [e] Disabled source: t3dcachedb.psi.ch:1094
----- End Fatal Exception -------------------------------------------------
logfile
pv_cfg.py
cp: cannot stat 'pv.root': No such file or directory
