HOME: /t3home/frejalom
USER: frejalom
SLURM_JOB_ID: 244146
HOSTNAME: t3wn58
CMSSW RELEASE BASE  /cvmfs/cms.cern.ch/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_2_0_pre4
%MSG-i AlpakaService:  (NoModuleName) 02-Apr-2025 08:45:16 CEST pre-events
AlpakaServiceSerialSync succesfully initialised.
Found 1 device:
  - Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
%MSG
02-Apr-2025 08:45:46 CEST  Initiating request to open file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root
[2025-04-02 08:45:47.242750 +0200][Error  ][XRootDTransport   ][59661] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:45:47.242944 +0200][Error  ][XRootDTransport   ][59661] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:45:47.243059 +0200][Error  ][AsyncSock         ][59661] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:45:47.243206 +0200][Error  ][PostMaster        ][59661] [t3dcachedb.psi.ch:1094] elapsed = 1, pConnectionWindow = 31 seconds.
[2025-04-02 08:45:47.243235 +0200][Error  ][PostMaster        ][59661] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:45:47.243261 +0200][Error  ][XRootD            ][59661] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root). Trying to recover.
[2025-04-02 08:45:47.243376 +0200][Error  ][XRootD            ][59661] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/5211ea53-d2cd-4f1e-b7ea-8b7c48ee827a.root). Trying to recover.
[2025-04-02 08:45:47.243430 +0200][Error  ][XRootD            ][59661] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: //pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/0c34fdf2-774c-4da4-8676-bfd61ef7cffd.root). Trying to recover.
[2025-04-02 08:45:47.243762 +0200][Error  ][XRootD            ][59661] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_query (code: kXR_Qconfig, arg length: 9). Trying to recover.
[2025-04-02 08:45:48.278498 +0200][Error  ][XRootDTransport   ][59661] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:45:48.278604 +0200][Error  ][XRootDTransport   ][59661] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:45:48.278623 +0200][Error  ][AsyncSock         ][59661] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:45:48.278670 +0200][Error  ][PostMaster        ][59661] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:45:48.278682 +0200][Error  ][PostMaster        ][59661] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:45:48.278693 +0200][Error  ][XRootD            ][59661] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:45:48 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root?xrdcl.requuid=4cea3063-0d3f-4bbf-8bbb-feb2087abde7.
%MSG
[2025-04-02 08:45:48.315273 +0200][Error  ][XRootDTransport   ][59661] [t3dcachedb.psi.ch:1094.0] Authentication with gsi failed: login failed
[2025-04-02 08:45:48.315383 +0200][Error  ][XRootDTransport   ][59661] [t3dcachedb.psi.ch:1094.0] No protocols left to try
[2025-04-02 08:45:48.315408 +0200][Error  ][AsyncSock         ][59661] [t3dcachedb.psi.ch:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2025-04-02 08:45:48.315465 +0200][Error  ][PostMaster        ][59661] [t3dcachedb.psi.ch:1094] elapsed = 0, pConnectionWindow = 31 seconds.
[2025-04-02 08:45:48.315482 +0200][Error  ][PostMaster        ][59661] [t3dcachedb.psi.ch:1094] Unable to recover: [FATAL] Auth failed.
[2025-04-02 08:45:48.315495 +0200][Error  ][XRootD            ][59661] [t3dcachedb.psi.ch:1094] Impossible to send message kXR_open (file: /pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root?tried=, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 02-Apr-2025 08:45:48 CEST pre-events
Failed to open file at URL root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root?tried=&xrdcl.requuid=62529c92-844d-4a0d-a423-580a04181784.
%MSG
----- Begin Fatal Exception 02-Apr-2025 08:45:48 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root'
   Additional Info:
      [a] Input file root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root could not be opened.
      [b] XrdCl::File::Open(name='root://t3dcachedb.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root', flags=0x10, permissions=0660) => error '[FATAL] Auth failed: No protocols left to try' (errno=0, code=204). No additional data servers were found.
      [c] Last URL tried: root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/werdmann/store/relval/CMSSW_14_2_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_141X_mcRun4_realistic_v3_STD_2026D110_PU-v2/2590000/7fdaaa50-5863-4108-b350-12036bf29ad0.root?tried=&xrdcl.requuid=62529c92-844d-4a0d-a423-580a04181784
      [d] Problematic data server: t3dcachedb.psi.ch:1094
      [e] Disabled source: t3dcachedb.psi.ch:1094
----- End Fatal Exception -------------------------------------------------
logfile
pv_cfg.py
cp: cannot stat 'pv.root': No such file or directory
